# DataSource settings
spring.datasource.username=sa
spring.datasource.password=sapassword
spring.sql.init.data-locations=classpath*:db/data.sql
spring.datasource.url=jdbc:h2:mem:travel_agency;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true